//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyProduct("Process Domain")]
[assembly: System.Reflection.AssemblyFileVersion("1.10.0.0")]
[assembly: System.Reflection.AssemblyVersion("1.10.0.0")]


