name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Install NuGet Packages
        run: nuget restore ProcessDomain.sln

      - name: Build
        run: msbuild ProcessDomain.sln

      - name: Run Tests
        working-directory: src\AppSecInc.ProcessDomain.UnitTests\bin\Debug
        run: vstest.console.exe AppSecInc.ProcessDomain.UnitTests.dll
