name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Get Release Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v1
        name: Checkout

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Install NuGet Packages
        run: nuget restore ProcessDomain.sln

      - name: Install MSBuildTasks Package
        run: nuget install MSBuildTasks -Version 1.5.0.235

      - name: Generate GlobalAssemblyInfo.cs
        run: msbuild .\Version.proj /p:Version=${{ steps.get_version.outputs.VERSION }}

      - name: Build Release
        run: msbuild ProcessDomain.sln /property:Configuration=Release

      - name: Create NuGet Package
        run: nuget pack .\AppSecInc.ProcessDomain.nuspec -p version=${{ steps.get_version.outputs.VERSION }}

      - name: Publish NuGet Package
        run: nuget push AppSecInc.ProcessDomain.${{ steps.get_version.outputs.VERSION }}.nupkg -Source https://api.nuget.org/v3/index.json
